name: jobs-java
on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - main
jobs:
  build-linux-java:
    runs-on: ubuntu-latest
    container:
      image: zjay437/rocksdb:0.6
    steps:
    - uses: actions/checkout@v4
    - uses: "./.github/actions/pre-steps"
    - name: Set Java Environment
      run: |-
        echo "JAVA_HOME=${JAVA_HOME}"
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
        which java && java -version
        which javac && javac -version
    - name: Test RocksDBJava
      run: |-
        cd /__w/encfs/encfs/rocksdb
        make V=1 J=4 -j4 jtest
    - uses: "./.github/actions/post-steps"
  build-linux-java-static:
    runs-on: ubuntu-latest
    container:
      image: zjay437/rocksdb:0.6
    steps:
    - uses: actions/checkout@v4
    - uses: "./.github/actions/pre-steps"
    - name: Set Java Environment
      run: |-
        echo "JAVA_HOME=${JAVA_HOME}"
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
        which java && java -version
        which javac && javac -version
    - name: Build RocksDBJava Static Library
      run: |-
        cd /__w/encfs/encfs/rocksdb
        make V=1 J=4 -j4 rocksdbjavastatic
    - uses: "./.github/actions/post-steps"
  build-macos-java:
    runs-on: macos-11
    env:
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
      ROCKSDB_DISABLE_JEMALLOC: 1
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/install-jdk8-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: Set Java Environment
      run: |-
        echo "JAVA_HOME=${JAVA_HOME}"
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
        which java && java -version
        which javac && javac -version
    - name: Test RocksDBJava
      run: echo "skip this job"
#      Undefined symbols for architecture x86_64:
#          "encfs_reg", referenced from:
#                         -u command line option
#                         (maybe you meant: _encfs_reg)
#      ld: symbol(s) not found for architecture x86_64
#      clang:
#        error: linker command failed with exit code 1 (use -v to see invocation)
#      make: *** [ rocksdbjava ] Error 1
#      run: |-
#        cd /Users/runner/work/encfs/encfs/rocksdb
#        make V=1 J=4 -j4 jtest
    - uses: "./.github/actions/post-steps"
  build-macos-java-static:
    runs-on: macos-11
    env:
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-jdk8-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: Set Java Environment
      run: |-
        echo "JAVA_HOME=${JAVA_HOME}"
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
        which java && java -version
        which javac && javac -version
    - name: Build RocksDBJava x86 and ARM Static Libraries
      run: echo "skip this job"
      # TODO(yingchun): resolve it
      # build error:
      #   Undefined symbols for architecture x86_64:
      #       "_AES_decrypt", referenced from:
      #                         rocksdb::encryption::AESBlockCipher::Decrypt(char*) in encryption.o
      #         "_AES_encrypt", referenced from:
      #                           rocksdb::encryption::AESCTRCipherStream::EncryptBlock(unsigned long long, char*, char*) in encryption.o
      #                           rocksdb::encryption::AESBlockCipher::Encrypt(char*) in encryption.o
      #         "_AES_set_decrypt_key", referenced from:
      #                                   rocksdb::encryption::AESBlockCipher::InitKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in encryption.o
      #         "_AES_set_encrypt_key", referenced from:
      #                                   rocksdb::encryption::AESBlockCipher::InitKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in encryption.o
      #   ld: symbol(s) not found for architecture x86_64
      #   clang: error: linker command failed with exit code 1 (use -v to see invocation)
      #   make[2]: *** [rocksdbjavastatic_javalib] Error 1
      #   make[1]: *** [rocksdbjavastaticosx_arch_x86_64] Error 2
      #   make: *** [rocksdbjavastaticosx_archs] Error 2
      #   Error: Process completed with exit code 2.
      # run: make V=1 J=4 -j4 rocksdbjavastaticosx
    - uses: "./.github/actions/post-steps"
  build-macos-java-static-universal:
    runs-on: macos-11
    env:
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-jdk8-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: Set Java Environment
      run: |-
        echo "JAVA_HOME=${JAVA_HOME}"
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV
        which java && java -version
        which javac && javac -version
    - name: Build RocksDBJava Universal Binary Static Library
      run: echo "skip this job"
      # TODO(yingchun): resolve it
      # build error:
      #   Undefined symbols for architecture x86_64:
      #       "_AES_decrypt", referenced from:
      #                         rocksdb::encryption::AESBlockCipher::Decrypt(char*) in encryption.o
      #         "_AES_encrypt", referenced from:
      #                           rocksdb::encryption::AESCTRCipherStream::EncryptBlock(unsigned long long, char*, char*) in encryption.o
      #                           rocksdb::encryption::AESBlockCipher::Encrypt(char*) in encryption.o
      #         "_AES_set_decrypt_key", referenced from:
      #                                   rocksdb::encryption::AESBlockCipher::InitKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in encryption.o
      #         "_AES_set_encrypt_key", referenced from:
      #                                   rocksdb::encryption::AESBlockCipher::InitKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in encryption.o
      #   ld: symbol(s) not found for architecture x86_64
      #   clang: error: linker command failed with exit code 1 (use -v to see invocation)
      #   make[2]: *** [rocksdbjavastatic_javalib] Error 1
      #   make[1]: *** [rocksdbjavastaticosx_arch_x86_64] Error 2
      #   make: *** [rocksdbjavastaticosx_archs] Error 2
      #   Error: Process completed with exit code 2.
      # run: make V=1 J=4 -j4 rocksdbjavastaticosx_ub
    - uses: "./.github/actions/post-steps"
